spring.application.name=reciclahub

# TODOS OS DADOS DE ACESSO
# SÃO FORNECIDOS PELA FACULDADE

# Endereço do banco de dados
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
# Usuário do banco de dados
spring.datasource.username=RM566522
# Senha do banco de dados
spring.datasource.password=100906

# Mostrar as instruções SQL
# executadas no banco de dados
spring.jpa.show-sql=true

# QUEBRAR A EXIBIÇÃO DA INSTRUÇÃO SQL EM VÁRIAS LINHAS
spring.jpa.properties.hibernate.format_sql=true

# CRIAR A TABELA DE CONTROLE DE MIGRAÇÃO NO BANCO DE DADOS
spring.flyway.baselineOnMigrate=true

# REMOVER O CAMPO "trace" DA RESPOSTA DE ERRO
#nos mostra toda a pilha de erros que foi gerada no servidor.
# Essa informação é importante para o desenvolvedor da API,
# mas não ao consumidor da API. Vamos removê-la mais adiante;
server.error.include-stacktrace=never
