CREATE SEQUENCE SEQ_EMPRESA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tbl_empresa (
    id_empresa NUMBER PRIMARY KEY,
    cnpj VARCHAR2(20) NOT NULL,
    nome VARCHAR2(255) NOT NULL,
    email VARCHAR2(255),
    senha VARCHAR2(255),
    tipo VARCHAR2(50)
);