CREATE SEQUENCE SEQ_TIPO_RESIDUO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE tbl_tipo_residuo (
    id_tipo NUMBER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(255),
    limite_maximo NUMBER
);