CREATE SEQUENCE SEQ_PONTO_COLETA
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE tbl_ponto_coleta (
    id_ponto NUMBER PRIMARY KEY NOT NULL,
    nome_local VARCHAR2(100) NOT NULL,
    endereco VARCHAR2(100) NOT NULL,
    capacidade_total NUMBER NOT NULL,
    id_empresa NUMBER NOT NULL
);